### ISSUE TITLE
flood on registration action - bluechictl list-units -> permission denied

### ISSUE THREAD

**Issue by dougsland** [engelmi/hirte#568] opened 2023-09-18 16:15 UTC
## Describe the bug

Identify why bluechictl is getting permission denied when flooding register flow. 

Question: Is this something in the client or Daemon?

1) Change the code to flood the registration.
```
git diff
diff --git a/src/agent/agent.c b/src/agent/agent.c
index b02500e..33196b1 100644
--- a/src/agent/agent.c
+++ b/src/agent/agent.c
@@ -2293,16 +2293,19 @@ static bool agent_connect(Agent *agent) {

         _cleanup_sd_bus_message_ sd_bus_message *bus_msg = NULL;
         sd_bus_error error = SD_BUS_ERROR_NULL;
-        r = sd_bus_call_method(
-                        agent->peer_dbus,
-                        BC_DBUS_NAME,
-                        INTERNAL_MANAGER_OBJECT_PATH,
-                        INTERNAL_MANAGER_INTERFACE,
-                        "Register",
-                        &error,
-                        &bus_msg,
-                        "s",
-                        agent->name);
+        for (int i = 1; i <= 100000; i++) {
+               bc_log_infof("FLOOD: Calling method to register # %d", i);
+                r = sd_bus_call_method(
+                                agent->peer_dbus,
+                                BC_DBUS_NAME,
+                                INTERNAL_MANAGER_OBJECT_PATH,
+                                INTERNAL_MANAGER_INTERFACE,
+                                "Register",
+                                &error,
+                                &bus_msg,
+                                "s",
+                                agent->name);
+        }
         if (r < 0) {
                 bc_log_errorf("Registering as '%s' failed: %s", agent->name, error.message);
                 sd_bus_error_free(&error);
```

2) Keep listing all nodes units, from time to time, I see bluechictl getting internal error like below:
```
# bluechictl list-units|more
Failed to issue method call: Internal error
Call to manager failed: Permission denied
```

In the logs:
```
Sep 13 17:38:55 node1 bluechi-agent[201552]: Registering as 'node1' failed: Unknown object '/org/eclipse/bluechi/internal'.
Sep 13 17:38:58 node1 bluechi-agent[201552]: Registering as 'node1' failed: Unknown object '/org/eclipse/bluechi/internal'.
Sep 13 17:39:00 node1 bluechi-agent[201552]: Registering as 'node1' failed: Unknown object '/org/eclipse/bluechi/internal'.
Sep 13 17:39:02 node1 bluechi-agent[201552]: Registering as 'node1' failed: Unknown object '/org/eclipse/bluechi/internal'.
Sep 13 17:39:04 node1 bluechi-agent[201552]: Registering as 'node1' failed: Unknown object '/org/eclipse/bluechi/internal'.
Sep 13 17:39:07 node1 bluechi-agent[201552]: Registering as 'node1' failed: Unknown object '/org/eclipse/bluechi/internal'.
Sep 13 17:39:09 node1 bluechi-agent[201552]: Registering as 'node1' failed: Unknown object '/org/eclipse/bluechi/internal'.
Sep 13 17:39:12 node1 bluechi-agent[201552]: Registering as 'node1' failed: Unknown object '/org/eclipse/bluechi/internal'.
Sep 13 17:39:13 node1 bluechi-agent[201552]: Registering as 'node1' failed: Unknown object '/org/eclipse/bluechi/internal'.
Sep 13 17:39:16 node1 bluechi-agent[201552]: Registering as 'node1' failed: Unknown object '/org/eclipse/bluechi/internal'.
Sep 13 17:39:18 node1 bluechi-agent[201552]: Registering as 'node1' failed: Unknown object '/org/eclipse/bluechi/internal'.
Sep 13 17:39:20 node1 bluechi-agent[201552]: Registering as 'node1' failed: Unknown object '/org/eclipse/bluechi/internal'.
```

@engelmi shared:
```
The Unknown object '/org/eclipse/bluechi/internal'. error is expected as you can only register once.
Since the agent only communicates via signals with the controller, I'd recommend just spamming signals, e.g.
heartbeat (https://github.com/containers/bluechi/blob/main/src/agent/agent.c#L139-L144)
or unit new (https://github.com/containers/bluechi/blob/main/src/agent/agent.c#L1180-L1187)
```

```
Background: After the first Register call we migrate the respective peer-to-peer dbus, which adds all the other interfaces e.g. for the heartbeat. But it also removes the vtable on that path /org/eclipse/bluechi/internal that contains interface with the Register method (we registered already, don't need it anymore).
```

```
Regarding the bluechictl : I assume you are running it as root and it still returns permission denied? When did you run it? Maybe when the register test was running?
```

**Comment by dougsland** [comment] 2023-09-18 16:16
@Yarboa

**Comment by engelmi** [comment] 2023-10-05 10:49
Its an interesting case how "breaking the protocol" between controller and agent can look like. Calling the register method only a second time is sufficient to reproduce that issue. I wouldn't consider the behavior in controller or agent a bug though since its just the protocol between both components and everything gets cleaned up properly.
But the error message in bluechictl that sometimes occurs should be improved... Failed to issue method call: Internal error doesn't really help much. It happens basically when the list-units request is issued and the peer bus is gone for that time frame - deeper down in the code stack you'd get a Device not found error. We need to improve the returned error messages in general - I'd close this issue and reference it as an example in https://github.com/containers/bluechi/issues/567

**Closed as completed by engelmi** 2023-10-05 10:49 UTC
Labels: bug
